apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-nlp-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-nlp-app
  template:
    metadata:
      labels:
        app: sample-nlp-app
    spec:
      containers:
      - name: sample-nlp-app
        image: svkk8sacr.azurecr.io/svkmsr6/sample-nlp-app
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sample-nlp-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  externalIPs:
    - 1.2.4.120
  selector:
    app: sample-nlp-app